services:
  building_1:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-1
    volumes:
      - /root/stormsmarthome/mqtt/data-file:/app/data-file
    environment:
      - HOSTNAME=10.1.0.167
      - CSV_FILE=house-0.csv
      - SPEED=100
    command: node index.js -f data-file/${CSV_FILE} -b ${HOSTNAME} -s ${SPEED}

  building_2:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-2
    volumes:
      - /root/stormsmarthome/mqtt/data-file:/app/data-file
    environment:
      - HOSTNAME=10.1.0.167
      - CSV_FILE=house-1.csv
      - SPEED=100
    command: node index.js -f data-file/${CSV_FILE} -b ${HOSTNAME} -s ${SPEED}

  building_3:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-3
    volumes:
      - /root/stormsmarthome/mqtt/data-file:/app/data-file
    environment:
      - HOSTNAME=10.1.0.167
      - CSV_FILE=house-2.csv
      - SPEED=100
    command: node index.js -f data-file/${CSV_FILE} -b ${HOSTNAME} -s ${SPEED}
